// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Web.Api.GeneratedCode.Contracts;

#nullable enable annotations

namespace Web.Api.GeneratedCode
{
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.6.5.0")]
    public partial interface IApiClient
    {
        [Headers("Accept: application/json")]
        [Get("/ebc/exchanges-rates")]
        Task<IApiResponse<ICollection<ExchangeRate>>> GetECBExchangesRatesAsync([Query] string source, CancellationToken cancellationToken = default);

        [Headers("Content-Type: application/json")]
        [Post("/ecb/exchanges-rates")]
        Task<IApiResponse> PostECBExchangesRatesAsync([Body] IEnumerable<ExchangeRate> body, CancellationToken cancellationToken = default);


    }

}